---
name: "NPM build"
"on":
  push:
    branches:
    - "main"
  pull_request:
    branches:
    - "main"
jobs:
  build:
    runs-on: "ubuntu-latest"
    env:
      GH_TOKEN: "${{ secrets.GH_TOKEN }}"
    steps:
    - uses: "actions/checkout@v5"
    - name: "Set up JDK 21"
      uses: "actions/setup-java@v5"
      with:
        distribution: "zulu"
        java-version: "21"
        java-package: "jdk"
        cache: "maven"
    - name: "Setup node"
      uses: "actions/setup-node@v5"
      with:
        node-version: "lts/*"
        cache: "npm"
        cache-dependency-path: "svelte/package-lock.json"
    - run: "node --version"
    - run: "npm --version"
    - run: "mvn --version"
    - run: "mvn -s settings.xml -pl playwright install"
    - run: "mvn -s settings.xml -pl playwright exec:java -Dexec.mainClass=com.microsoft.playwright.CLI\
        \ -Dexec.args=\"install --with-deps\""
    - run: "make M='mvn -s settings.xml' clean"
    - run: "make M='mvn -s settings.xml' fmtCheck"
    - run: "make -C svelte"
    - run: "make -C svelte lint"
    - run: "make -C svelte package"
    - run: "make -C svelte build"
    - run: "make -C svelte test"
    - run: "make M='mvn -s settings.xml'"
    - name: "Submit Dependency Snapshot"
      uses: "advanced-security/maven-dependency-submission-action@v5"
      with:
        token: "${{ secrets.GH_TOKEN }}"
        maven-args: "-s settings.xml"
