---
name: "NPM build"
"on":
  push:
    branches:
    - "main"
  pull_request:
    branches:
    - "main"
jobs:
  build:
    runs-on: "ubuntu-latest"
    env:
      GH_TOKEN: "${{ secrets.GH_TOKEN }}"
    steps:
    - uses: "actions/checkout@v4"
    - name: "Set up JDK 23"
      uses: "actions/setup-java@v4"
      with:
        distribution: "zulu"
        java-version: "23"
        java-package: "jdk"
        cache: "maven"
    - name: "Setup node"
      uses: "actions/setup-node@v4"
      with:
        node-version: 20
        cache: "npm"
        cache-dependency-path: "svelte/package-lock.json"
    - run: "node --version"
    - run: "npm --version"
    - run: "mvn --version"
    - run: "mvn -s settings.xml -pl playwright --no-transfer-progress install"
    - run: "mvn -s settings.xml -pl playwright exec:java -Dexec.mainClass=com.microsoft.playwright.CLI\
        \ -Dexec.args=\"install --with-deps\""
    - run: "make M='mvn -s settings.xml' fmtCheck"
    - run: "make -C svelte"
    - run: "make -C svelte lint"
    - run: "make -C svelte test"
    - run: "make -C svelte package"
    - run: "make -C svelte build"
    - run: "make M='mvn -s settings.xml'"
