---
name: "NPM build"
"on":
  push:
    branches:
    - "main"
  pull_request:
    branches:
    - "main"
jobs:
  build:
    runs-on: "ubuntu-latest"
    env:
      GH_TOKEN: "${{ secrets.GH_TOKEN }}"
    steps:
    - uses: "actions/checkout@v4"
    - name: "Setup node"
      uses: "actions/setup-node@v4"
      with:
        node-version: 20
        cache: "npm"
        cache-dependency-path: "svelte/package-lock.json"
    - run: "node --version"
    - run: "npm --version"
    - run: "mvn --version"
    - run: "make M='mvn -s settings.xml' fmtCheck"
    - run: "make -C svelte lint"
    - run: "make -C svelte test"
    - run: "make -C svelte package"
    - run: "make -C svelte build"
    - run: "make M='mvn -s settings.xml'"
