---
name: "Deploy Tag"
"on":
  create:
    tags:
    - "*"
jobs:
  build:
    runs-on: "ubuntu-latest"
    env:
      GH_TOKEN: "${{ secrets.GH_TOKEN }}"
    steps:
    - uses: "actions/checkout@v4"
    - name: "Set up JDK 22"
      uses: "actions/setup-java@v4"
      with:
        distribution: "zulu"
        java-version: "22"
        java-package: "jdk"
        cache: "maven"
    - name: "Setup node"
      uses: "actions/setup-node@v4"
      with:
        node-version: 20
        cache: "npm"
        cache-dependency-path: "svelte/package-lock.json"
    - run: "npm set \"//npm.pkg.github.com/:_authToken=$GH_TOKEN\""
    - run: "node --version"
    - run: "npm --version"
    - run: "mvn --version"
    - run: "make M='mvn -s settings.xml' fmtCheck"
    - run: "make -C svelte lint"
    - run: "make -C svelte test"
    - run: "make -C svelte package"
    - run: "make -C svelte build"
    - run: "make -C svelte publish"
    - run: "make M='mvn -s settings.xml'"
    - run: "make M='mvn -s settings.xml' deploy"
    - name: "Release"
      uses: "softprops/action-gh-release@v2"
      with:
        generate_release_notes: "true"
        make_latest: "true"
        token: "${{ secrets.GH_TOKEN }}"
